# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/json.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/json.proto\x12\x04json\x1a google/protobuf/descriptor.proto\"A\n\x0eMessageOptions\x12\x0e\n\x06ignore\x18\x02 \x01(\x08\x12\x1f\n\x17\x64isallow_unknown_fields\x18\x06 \x01(\x08\"[\n\x0cOneofOptions\x12\x11\n\x04json\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0e\n\x06ignore\x18\x02 \x01(\x08\x12\x11\n\tomitempty\x18\x03 \x01(\x08\x12\x0c\n\x04hide\x18\x04 \x01(\x08\x42\x07\n\x05_json\"f\n\x0c\x46ieldOptions\x12\x11\n\x04json\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0e\n\x06ignore\x18\x02 \x01(\x08\x12\x11\n\tomitempty\x18\x03 \x01(\x08\x12\x17\n\x0fuse_enum_string\x18\x04 \x01(\x08\x42\x07\n\x05_json:H\n\x07message\x12\x1f.google.protobuf.MessageOptions\x18\xa0\xf4\x03 \x01(\x0b\x32\x14.json.MessageOptions:B\n\x05\x66ield\x12\x1d.google.protobuf.FieldOptions\x18\xa1\xf4\x03 \x01(\x0b\x32\x12.json.FieldOptions:B\n\x05oneof\x12\x1d.google.protobuf.OneofOptions\x18\xa2\xf4\x03 \x01(\x0b\x32\x12.json.OneofOptionsB]\n\x1fio.github.yu31.protoc.pb.pbjsonB\x06PBJSONP\x01Z0github.com/yu31/protoc-plugin-json/xgo/pb/pbjsonb\x06proto3')


MESSAGE_FIELD_NUMBER = 64032
message = DESCRIPTOR.extensions_by_name['message']
FIELD_FIELD_NUMBER = 64033
field = DESCRIPTOR.extensions_by_name['field']
ONEOF_FIELD_NUMBER = 64034
oneof = DESCRIPTOR.extensions_by_name['oneof']

_MESSAGEOPTIONS = DESCRIPTOR.message_types_by_name['MessageOptions']
_ONEOFOPTIONS = DESCRIPTOR.message_types_by_name['OneofOptions']
_FIELDOPTIONS = DESCRIPTOR.message_types_by_name['FieldOptions']
MessageOptions = _reflection.GeneratedProtocolMessageType('MessageOptions', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEOPTIONS,
  '__module__' : 'proto.json_pb2'
  # @@protoc_insertion_point(class_scope:json.MessageOptions)
  })
_sym_db.RegisterMessage(MessageOptions)

OneofOptions = _reflection.GeneratedProtocolMessageType('OneofOptions', (_message.Message,), {
  'DESCRIPTOR' : _ONEOFOPTIONS,
  '__module__' : 'proto.json_pb2'
  # @@protoc_insertion_point(class_scope:json.OneofOptions)
  })
_sym_db.RegisterMessage(OneofOptions)

FieldOptions = _reflection.GeneratedProtocolMessageType('FieldOptions', (_message.Message,), {
  'DESCRIPTOR' : _FIELDOPTIONS,
  '__module__' : 'proto.json_pb2'
  # @@protoc_insertion_point(class_scope:json.FieldOptions)
  })
_sym_db.RegisterMessage(FieldOptions)

if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(message)
  google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(field)
  google_dot_protobuf_dot_descriptor__pb2.OneofOptions.RegisterExtension(oneof)

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037io.github.yu31.protoc.pb.pbjsonB\006PBJSONP\001Z0github.com/yu31/protoc-plugin-json/xgo/pb/pbjson'
  _MESSAGEOPTIONS._serialized_start=60
  _MESSAGEOPTIONS._serialized_end=125
  _ONEOFOPTIONS._serialized_start=127
  _ONEOFOPTIONS._serialized_end=218
  _FIELDOPTIONS._serialized_start=220
  _FIELDOPTIONS._serialized_end=322
# @@protoc_insertion_point(module_scope)
