// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: json.proto

package io.github.yu31.protoc.pb.pbjson;

/**
 * <pre>
 * TODO: unsupported the type of bool as map key same as the standard JSON.
 * </pre>
 *
 * Protobuf type {@code json.FieldOptions}
 */
public final class FieldOptions extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:json.FieldOptions)
    FieldOptionsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FieldOptions.newBuilder() to construct.
  private FieldOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FieldOptions() {
    json_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FieldOptions();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FieldOptions(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            json_ = s;
            break;
          }
          case 16: {

            ignore_ = input.readBool();
            break;
          }
          case 24: {

            omitempty_ = input.readBool();
            break;
          }
          case 32: {

            useEnumString_ = input.readBool();
            break;
          }
          case 90: {
            io.github.yu31.protoc.pb.pbjson.TypeEnum.Builder subBuilder = null;
            if (wKTCase_ == 11) {
              subBuilder = ((io.github.yu31.protoc.pb.pbjson.TypeEnum) wKT_).toBuilder();
            }
            wKT_ =
                input.readMessage(io.github.yu31.protoc.pb.pbjson.TypeEnum.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.github.yu31.protoc.pb.pbjson.TypeEnum) wKT_);
              wKT_ = subBuilder.buildPartial();
            }
            wKTCase_ = 11;
            break;
          }
          case 98: {
            io.github.yu31.protoc.pb.pbjson.TypeAny.Builder subBuilder = null;
            if (wKTCase_ == 12) {
              subBuilder = ((io.github.yu31.protoc.pb.pbjson.TypeAny) wKT_).toBuilder();
            }
            wKT_ =
                input.readMessage(io.github.yu31.protoc.pb.pbjson.TypeAny.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.github.yu31.protoc.pb.pbjson.TypeAny) wKT_);
              wKT_ = subBuilder.buildPartial();
            }
            wKTCase_ = 12;
            break;
          }
          case 106: {
            io.github.yu31.protoc.pb.pbjson.TypeDuration.Builder subBuilder = null;
            if (wKTCase_ == 13) {
              subBuilder = ((io.github.yu31.protoc.pb.pbjson.TypeDuration) wKT_).toBuilder();
            }
            wKT_ =
                input.readMessage(io.github.yu31.protoc.pb.pbjson.TypeDuration.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.github.yu31.protoc.pb.pbjson.TypeDuration) wKT_);
              wKT_ = subBuilder.buildPartial();
            }
            wKTCase_ = 13;
            break;
          }
          case 114: {
            io.github.yu31.protoc.pb.pbjson.TypeTimestamp.Builder subBuilder = null;
            if (wKTCase_ == 14) {
              subBuilder = ((io.github.yu31.protoc.pb.pbjson.TypeTimestamp) wKT_).toBuilder();
            }
            wKT_ =
                input.readMessage(io.github.yu31.protoc.pb.pbjson.TypeTimestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.github.yu31.protoc.pb.pbjson.TypeTimestamp) wKT_);
              wKT_ = subBuilder.buildPartial();
            }
            wKTCase_ = 14;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.yu31.protoc.pb.pbjson.PBJSON.internal_static_json_FieldOptions_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.yu31.protoc.pb.pbjson.PBJSON.internal_static_json_FieldOptions_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.yu31.protoc.pb.pbjson.FieldOptions.class, io.github.yu31.protoc.pb.pbjson.FieldOptions.Builder.class);
  }

  private int bitField0_;
  private int wKTCase_ = 0;
  private java.lang.Object wKT_;
  public enum WKTCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    ENUM(11),
    ANY(12),
    DURATION(13),
    TIMESTAMP(14),
    WKT_NOT_SET(0);
    private final int value;
    private WKTCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static WKTCase valueOf(int value) {
      return forNumber(value);
    }

    public static WKTCase forNumber(int value) {
      switch (value) {
        case 11: return ENUM;
        case 12: return ANY;
        case 13: return DURATION;
        case 14: return TIMESTAMP;
        case 0: return WKT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public WKTCase
  getWKTCase() {
    return WKTCase.forNumber(
        wKTCase_);
  }

  public static final int JSON_FIELD_NUMBER = 1;
  private volatile java.lang.Object json_;
  /**
   * <pre>
   * The key name in json format. Default is field's name in proto.
   * If "json" is "-", The field will be ignore.
   * </pre>
   *
   * <code>optional string json = 1;</code>
   * @return Whether the json field is set.
   */
  @java.lang.Override
  public boolean hasJson() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The key name in json format. Default is field's name in proto.
   * If "json" is "-", The field will be ignore.
   * </pre>
   *
   * <code>optional string json = 1;</code>
   * @return The json.
   */
  @java.lang.Override
  public java.lang.String getJson() {
    java.lang.Object ref = json_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      json_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The key name in json format. Default is field's name in proto.
   * If "json" is "-", The field will be ignore.
   * </pre>
   *
   * <code>optional string json = 1;</code>
   * @return The bytes for json.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJsonBytes() {
    java.lang.Object ref = json_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      json_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IGNORE_FIELD_NUMBER = 2;
  private boolean ignore_;
  /**
   * <pre>
   * If true, the field will be ignore. It same as `json: "-"`
   * </pre>
   *
   * <code>bool ignore = 2;</code>
   * @return The ignore.
   */
  @java.lang.Override
  public boolean getIgnore() {
    return ignore_;
  }

  public static final int OMITEMPTY_FIELD_NUMBER = 3;
  private boolean omitempty_;
  /**
   * <pre>
   * Whether omit the field of empty value in encoding(MarshalJSON).
   * It same as the struct tag `json:"xxx,omitempty"`.
   * </pre>
   *
   * <code>bool omitempty = 3;</code>
   * @return The omitempty.
   */
  @java.lang.Override
  public boolean getOmitempty() {
    return omitempty_;
  }

  public static final int USE_ENUM_STRING_FIELD_NUMBER = 4;
  private boolean useEnumString_;
  /**
   * <pre>
   * Whether use string format for enum type. default use integer.
   * </pre>
   *
   * <code>bool use_enum_string = 4;</code>
   * @return The useEnumString.
   */
  @java.lang.Override
  public boolean getUseEnumString() {
    return useEnumString_;
  }

  public static final int ENUM_FIELD_NUMBER = 11;
  /**
   * <code>.json.TypeEnum enum = 11;</code>
   * @return Whether the enum field is set.
   */
  @java.lang.Override
  public boolean hasEnum() {
    return wKTCase_ == 11;
  }
  /**
   * <code>.json.TypeEnum enum = 11;</code>
   * @return The enum.
   */
  @java.lang.Override
  public io.github.yu31.protoc.pb.pbjson.TypeEnum getEnum() {
    if (wKTCase_ == 11) {
       return (io.github.yu31.protoc.pb.pbjson.TypeEnum) wKT_;
    }
    return io.github.yu31.protoc.pb.pbjson.TypeEnum.getDefaultInstance();
  }
  /**
   * <code>.json.TypeEnum enum = 11;</code>
   */
  @java.lang.Override
  public io.github.yu31.protoc.pb.pbjson.TypeEnumOrBuilder getEnumOrBuilder() {
    if (wKTCase_ == 11) {
       return (io.github.yu31.protoc.pb.pbjson.TypeEnum) wKT_;
    }
    return io.github.yu31.protoc.pb.pbjson.TypeEnum.getDefaultInstance();
  }

  public static final int ANY_FIELD_NUMBER = 12;
  /**
   * <code>.json.TypeAny any = 12;</code>
   * @return Whether the any field is set.
   */
  @java.lang.Override
  public boolean hasAny() {
    return wKTCase_ == 12;
  }
  /**
   * <code>.json.TypeAny any = 12;</code>
   * @return The any.
   */
  @java.lang.Override
  public io.github.yu31.protoc.pb.pbjson.TypeAny getAny() {
    if (wKTCase_ == 12) {
       return (io.github.yu31.protoc.pb.pbjson.TypeAny) wKT_;
    }
    return io.github.yu31.protoc.pb.pbjson.TypeAny.getDefaultInstance();
  }
  /**
   * <code>.json.TypeAny any = 12;</code>
   */
  @java.lang.Override
  public io.github.yu31.protoc.pb.pbjson.TypeAnyOrBuilder getAnyOrBuilder() {
    if (wKTCase_ == 12) {
       return (io.github.yu31.protoc.pb.pbjson.TypeAny) wKT_;
    }
    return io.github.yu31.protoc.pb.pbjson.TypeAny.getDefaultInstance();
  }

  public static final int DURATION_FIELD_NUMBER = 13;
  /**
   * <code>.json.TypeDuration duration = 13;</code>
   * @return Whether the duration field is set.
   */
  @java.lang.Override
  public boolean hasDuration() {
    return wKTCase_ == 13;
  }
  /**
   * <code>.json.TypeDuration duration = 13;</code>
   * @return The duration.
   */
  @java.lang.Override
  public io.github.yu31.protoc.pb.pbjson.TypeDuration getDuration() {
    if (wKTCase_ == 13) {
       return (io.github.yu31.protoc.pb.pbjson.TypeDuration) wKT_;
    }
    return io.github.yu31.protoc.pb.pbjson.TypeDuration.getDefaultInstance();
  }
  /**
   * <code>.json.TypeDuration duration = 13;</code>
   */
  @java.lang.Override
  public io.github.yu31.protoc.pb.pbjson.TypeDurationOrBuilder getDurationOrBuilder() {
    if (wKTCase_ == 13) {
       return (io.github.yu31.protoc.pb.pbjson.TypeDuration) wKT_;
    }
    return io.github.yu31.protoc.pb.pbjson.TypeDuration.getDefaultInstance();
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 14;
  /**
   * <code>.json.TypeTimestamp timestamp = 14;</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return wKTCase_ == 14;
  }
  /**
   * <code>.json.TypeTimestamp timestamp = 14;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public io.github.yu31.protoc.pb.pbjson.TypeTimestamp getTimestamp() {
    if (wKTCase_ == 14) {
       return (io.github.yu31.protoc.pb.pbjson.TypeTimestamp) wKT_;
    }
    return io.github.yu31.protoc.pb.pbjson.TypeTimestamp.getDefaultInstance();
  }
  /**
   * <code>.json.TypeTimestamp timestamp = 14;</code>
   */
  @java.lang.Override
  public io.github.yu31.protoc.pb.pbjson.TypeTimestampOrBuilder getTimestampOrBuilder() {
    if (wKTCase_ == 14) {
       return (io.github.yu31.protoc.pb.pbjson.TypeTimestamp) wKT_;
    }
    return io.github.yu31.protoc.pb.pbjson.TypeTimestamp.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, json_);
    }
    if (ignore_ != false) {
      output.writeBool(2, ignore_);
    }
    if (omitempty_ != false) {
      output.writeBool(3, omitempty_);
    }
    if (useEnumString_ != false) {
      output.writeBool(4, useEnumString_);
    }
    if (wKTCase_ == 11) {
      output.writeMessage(11, (io.github.yu31.protoc.pb.pbjson.TypeEnum) wKT_);
    }
    if (wKTCase_ == 12) {
      output.writeMessage(12, (io.github.yu31.protoc.pb.pbjson.TypeAny) wKT_);
    }
    if (wKTCase_ == 13) {
      output.writeMessage(13, (io.github.yu31.protoc.pb.pbjson.TypeDuration) wKT_);
    }
    if (wKTCase_ == 14) {
      output.writeMessage(14, (io.github.yu31.protoc.pb.pbjson.TypeTimestamp) wKT_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, json_);
    }
    if (ignore_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, ignore_);
    }
    if (omitempty_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, omitempty_);
    }
    if (useEnumString_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, useEnumString_);
    }
    if (wKTCase_ == 11) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, (io.github.yu31.protoc.pb.pbjson.TypeEnum) wKT_);
    }
    if (wKTCase_ == 12) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, (io.github.yu31.protoc.pb.pbjson.TypeAny) wKT_);
    }
    if (wKTCase_ == 13) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, (io.github.yu31.protoc.pb.pbjson.TypeDuration) wKT_);
    }
    if (wKTCase_ == 14) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, (io.github.yu31.protoc.pb.pbjson.TypeTimestamp) wKT_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.yu31.protoc.pb.pbjson.FieldOptions)) {
      return super.equals(obj);
    }
    io.github.yu31.protoc.pb.pbjson.FieldOptions other = (io.github.yu31.protoc.pb.pbjson.FieldOptions) obj;

    if (hasJson() != other.hasJson()) return false;
    if (hasJson()) {
      if (!getJson()
          .equals(other.getJson())) return false;
    }
    if (getIgnore()
        != other.getIgnore()) return false;
    if (getOmitempty()
        != other.getOmitempty()) return false;
    if (getUseEnumString()
        != other.getUseEnumString()) return false;
    if (!getWKTCase().equals(other.getWKTCase())) return false;
    switch (wKTCase_) {
      case 11:
        if (!getEnum()
            .equals(other.getEnum())) return false;
        break;
      case 12:
        if (!getAny()
            .equals(other.getAny())) return false;
        break;
      case 13:
        if (!getDuration()
            .equals(other.getDuration())) return false;
        break;
      case 14:
        if (!getTimestamp()
            .equals(other.getTimestamp())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasJson()) {
      hash = (37 * hash) + JSON_FIELD_NUMBER;
      hash = (53 * hash) + getJson().hashCode();
    }
    hash = (37 * hash) + IGNORE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIgnore());
    hash = (37 * hash) + OMITEMPTY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getOmitempty());
    hash = (37 * hash) + USE_ENUM_STRING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getUseEnumString());
    switch (wKTCase_) {
      case 11:
        hash = (37 * hash) + ENUM_FIELD_NUMBER;
        hash = (53 * hash) + getEnum().hashCode();
        break;
      case 12:
        hash = (37 * hash) + ANY_FIELD_NUMBER;
        hash = (53 * hash) + getAny().hashCode();
        break;
      case 13:
        hash = (37 * hash) + DURATION_FIELD_NUMBER;
        hash = (53 * hash) + getDuration().hashCode();
        break;
      case 14:
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.yu31.protoc.pb.pbjson.FieldOptions parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.yu31.protoc.pb.pbjson.FieldOptions parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbjson.FieldOptions parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.yu31.protoc.pb.pbjson.FieldOptions parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbjson.FieldOptions parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.yu31.protoc.pb.pbjson.FieldOptions parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbjson.FieldOptions parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.yu31.protoc.pb.pbjson.FieldOptions parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbjson.FieldOptions parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.github.yu31.protoc.pb.pbjson.FieldOptions parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbjson.FieldOptions parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.yu31.protoc.pb.pbjson.FieldOptions parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.yu31.protoc.pb.pbjson.FieldOptions prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * TODO: unsupported the type of bool as map key same as the standard JSON.
   * </pre>
   *
   * Protobuf type {@code json.FieldOptions}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:json.FieldOptions)
      io.github.yu31.protoc.pb.pbjson.FieldOptionsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.yu31.protoc.pb.pbjson.PBJSON.internal_static_json_FieldOptions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.yu31.protoc.pb.pbjson.PBJSON.internal_static_json_FieldOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.yu31.protoc.pb.pbjson.FieldOptions.class, io.github.yu31.protoc.pb.pbjson.FieldOptions.Builder.class);
    }

    // Construct using io.github.yu31.protoc.pb.pbjson.FieldOptions.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      json_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      ignore_ = false;

      omitempty_ = false;

      useEnumString_ = false;

      wKTCase_ = 0;
      wKT_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.yu31.protoc.pb.pbjson.PBJSON.internal_static_json_FieldOptions_descriptor;
    }

    @java.lang.Override
    public io.github.yu31.protoc.pb.pbjson.FieldOptions getDefaultInstanceForType() {
      return io.github.yu31.protoc.pb.pbjson.FieldOptions.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.yu31.protoc.pb.pbjson.FieldOptions build() {
      io.github.yu31.protoc.pb.pbjson.FieldOptions result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.yu31.protoc.pb.pbjson.FieldOptions buildPartial() {
      io.github.yu31.protoc.pb.pbjson.FieldOptions result = new io.github.yu31.protoc.pb.pbjson.FieldOptions(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.json_ = json_;
      result.ignore_ = ignore_;
      result.omitempty_ = omitempty_;
      result.useEnumString_ = useEnumString_;
      if (wKTCase_ == 11) {
        if (enumBuilder_ == null) {
          result.wKT_ = wKT_;
        } else {
          result.wKT_ = enumBuilder_.build();
        }
      }
      if (wKTCase_ == 12) {
        if (anyBuilder_ == null) {
          result.wKT_ = wKT_;
        } else {
          result.wKT_ = anyBuilder_.build();
        }
      }
      if (wKTCase_ == 13) {
        if (durationBuilder_ == null) {
          result.wKT_ = wKT_;
        } else {
          result.wKT_ = durationBuilder_.build();
        }
      }
      if (wKTCase_ == 14) {
        if (timestampBuilder_ == null) {
          result.wKT_ = wKT_;
        } else {
          result.wKT_ = timestampBuilder_.build();
        }
      }
      result.bitField0_ = to_bitField0_;
      result.wKTCase_ = wKTCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.yu31.protoc.pb.pbjson.FieldOptions) {
        return mergeFrom((io.github.yu31.protoc.pb.pbjson.FieldOptions)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.yu31.protoc.pb.pbjson.FieldOptions other) {
      if (other == io.github.yu31.protoc.pb.pbjson.FieldOptions.getDefaultInstance()) return this;
      if (other.hasJson()) {
        bitField0_ |= 0x00000001;
        json_ = other.json_;
        onChanged();
      }
      if (other.getIgnore() != false) {
        setIgnore(other.getIgnore());
      }
      if (other.getOmitempty() != false) {
        setOmitempty(other.getOmitempty());
      }
      if (other.getUseEnumString() != false) {
        setUseEnumString(other.getUseEnumString());
      }
      switch (other.getWKTCase()) {
        case ENUM: {
          mergeEnum(other.getEnum());
          break;
        }
        case ANY: {
          mergeAny(other.getAny());
          break;
        }
        case DURATION: {
          mergeDuration(other.getDuration());
          break;
        }
        case TIMESTAMP: {
          mergeTimestamp(other.getTimestamp());
          break;
        }
        case WKT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.github.yu31.protoc.pb.pbjson.FieldOptions parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.github.yu31.protoc.pb.pbjson.FieldOptions) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int wKTCase_ = 0;
    private java.lang.Object wKT_;
    public WKTCase
        getWKTCase() {
      return WKTCase.forNumber(
          wKTCase_);
    }

    public Builder clearWKT() {
      wKTCase_ = 0;
      wKT_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private java.lang.Object json_ = "";
    /**
     * <pre>
     * The key name in json format. Default is field's name in proto.
     * If "json" is "-", The field will be ignore.
     * </pre>
     *
     * <code>optional string json = 1;</code>
     * @return Whether the json field is set.
     */
    public boolean hasJson() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The key name in json format. Default is field's name in proto.
     * If "json" is "-", The field will be ignore.
     * </pre>
     *
     * <code>optional string json = 1;</code>
     * @return The json.
     */
    public java.lang.String getJson() {
      java.lang.Object ref = json_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        json_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The key name in json format. Default is field's name in proto.
     * If "json" is "-", The field will be ignore.
     * </pre>
     *
     * <code>optional string json = 1;</code>
     * @return The bytes for json.
     */
    public com.google.protobuf.ByteString
        getJsonBytes() {
      java.lang.Object ref = json_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        json_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The key name in json format. Default is field's name in proto.
     * If "json" is "-", The field will be ignore.
     * </pre>
     *
     * <code>optional string json = 1;</code>
     * @param value The json to set.
     * @return This builder for chaining.
     */
    public Builder setJson(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      json_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The key name in json format. Default is field's name in proto.
     * If "json" is "-", The field will be ignore.
     * </pre>
     *
     * <code>optional string json = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearJson() {
      bitField0_ = (bitField0_ & ~0x00000001);
      json_ = getDefaultInstance().getJson();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The key name in json format. Default is field's name in proto.
     * If "json" is "-", The field will be ignore.
     * </pre>
     *
     * <code>optional string json = 1;</code>
     * @param value The bytes for json to set.
     * @return This builder for chaining.
     */
    public Builder setJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      json_ = value;
      onChanged();
      return this;
    }

    private boolean ignore_ ;
    /**
     * <pre>
     * If true, the field will be ignore. It same as `json: "-"`
     * </pre>
     *
     * <code>bool ignore = 2;</code>
     * @return The ignore.
     */
    @java.lang.Override
    public boolean getIgnore() {
      return ignore_;
    }
    /**
     * <pre>
     * If true, the field will be ignore. It same as `json: "-"`
     * </pre>
     *
     * <code>bool ignore = 2;</code>
     * @param value The ignore to set.
     * @return This builder for chaining.
     */
    public Builder setIgnore(boolean value) {
      
      ignore_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If true, the field will be ignore. It same as `json: "-"`
     * </pre>
     *
     * <code>bool ignore = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIgnore() {
      
      ignore_ = false;
      onChanged();
      return this;
    }

    private boolean omitempty_ ;
    /**
     * <pre>
     * Whether omit the field of empty value in encoding(MarshalJSON).
     * It same as the struct tag `json:"xxx,omitempty"`.
     * </pre>
     *
     * <code>bool omitempty = 3;</code>
     * @return The omitempty.
     */
    @java.lang.Override
    public boolean getOmitempty() {
      return omitempty_;
    }
    /**
     * <pre>
     * Whether omit the field of empty value in encoding(MarshalJSON).
     * It same as the struct tag `json:"xxx,omitempty"`.
     * </pre>
     *
     * <code>bool omitempty = 3;</code>
     * @param value The omitempty to set.
     * @return This builder for chaining.
     */
    public Builder setOmitempty(boolean value) {
      
      omitempty_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether omit the field of empty value in encoding(MarshalJSON).
     * It same as the struct tag `json:"xxx,omitempty"`.
     * </pre>
     *
     * <code>bool omitempty = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOmitempty() {
      
      omitempty_ = false;
      onChanged();
      return this;
    }

    private boolean useEnumString_ ;
    /**
     * <pre>
     * Whether use string format for enum type. default use integer.
     * </pre>
     *
     * <code>bool use_enum_string = 4;</code>
     * @return The useEnumString.
     */
    @java.lang.Override
    public boolean getUseEnumString() {
      return useEnumString_;
    }
    /**
     * <pre>
     * Whether use string format for enum type. default use integer.
     * </pre>
     *
     * <code>bool use_enum_string = 4;</code>
     * @param value The useEnumString to set.
     * @return This builder for chaining.
     */
    public Builder setUseEnumString(boolean value) {
      
      useEnumString_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether use string format for enum type. default use integer.
     * </pre>
     *
     * <code>bool use_enum_string = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUseEnumString() {
      
      useEnumString_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.github.yu31.protoc.pb.pbjson.TypeEnum, io.github.yu31.protoc.pb.pbjson.TypeEnum.Builder, io.github.yu31.protoc.pb.pbjson.TypeEnumOrBuilder> enumBuilder_;
    /**
     * <code>.json.TypeEnum enum = 11;</code>
     * @return Whether the enum field is set.
     */
    @java.lang.Override
    public boolean hasEnum() {
      return wKTCase_ == 11;
    }
    /**
     * <code>.json.TypeEnum enum = 11;</code>
     * @return The enum.
     */
    @java.lang.Override
    public io.github.yu31.protoc.pb.pbjson.TypeEnum getEnum() {
      if (enumBuilder_ == null) {
        if (wKTCase_ == 11) {
          return (io.github.yu31.protoc.pb.pbjson.TypeEnum) wKT_;
        }
        return io.github.yu31.protoc.pb.pbjson.TypeEnum.getDefaultInstance();
      } else {
        if (wKTCase_ == 11) {
          return enumBuilder_.getMessage();
        }
        return io.github.yu31.protoc.pb.pbjson.TypeEnum.getDefaultInstance();
      }
    }
    /**
     * <code>.json.TypeEnum enum = 11;</code>
     */
    public Builder setEnum(io.github.yu31.protoc.pb.pbjson.TypeEnum value) {
      if (enumBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        wKT_ = value;
        onChanged();
      } else {
        enumBuilder_.setMessage(value);
      }
      wKTCase_ = 11;
      return this;
    }
    /**
     * <code>.json.TypeEnum enum = 11;</code>
     */
    public Builder setEnum(
        io.github.yu31.protoc.pb.pbjson.TypeEnum.Builder builderForValue) {
      if (enumBuilder_ == null) {
        wKT_ = builderForValue.build();
        onChanged();
      } else {
        enumBuilder_.setMessage(builderForValue.build());
      }
      wKTCase_ = 11;
      return this;
    }
    /**
     * <code>.json.TypeEnum enum = 11;</code>
     */
    public Builder mergeEnum(io.github.yu31.protoc.pb.pbjson.TypeEnum value) {
      if (enumBuilder_ == null) {
        if (wKTCase_ == 11 &&
            wKT_ != io.github.yu31.protoc.pb.pbjson.TypeEnum.getDefaultInstance()) {
          wKT_ = io.github.yu31.protoc.pb.pbjson.TypeEnum.newBuilder((io.github.yu31.protoc.pb.pbjson.TypeEnum) wKT_)
              .mergeFrom(value).buildPartial();
        } else {
          wKT_ = value;
        }
        onChanged();
      } else {
        if (wKTCase_ == 11) {
          enumBuilder_.mergeFrom(value);
        }
        enumBuilder_.setMessage(value);
      }
      wKTCase_ = 11;
      return this;
    }
    /**
     * <code>.json.TypeEnum enum = 11;</code>
     */
    public Builder clearEnum() {
      if (enumBuilder_ == null) {
        if (wKTCase_ == 11) {
          wKTCase_ = 0;
          wKT_ = null;
          onChanged();
        }
      } else {
        if (wKTCase_ == 11) {
          wKTCase_ = 0;
          wKT_ = null;
        }
        enumBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.json.TypeEnum enum = 11;</code>
     */
    public io.github.yu31.protoc.pb.pbjson.TypeEnum.Builder getEnumBuilder() {
      return getEnumFieldBuilder().getBuilder();
    }
    /**
     * <code>.json.TypeEnum enum = 11;</code>
     */
    @java.lang.Override
    public io.github.yu31.protoc.pb.pbjson.TypeEnumOrBuilder getEnumOrBuilder() {
      if ((wKTCase_ == 11) && (enumBuilder_ != null)) {
        return enumBuilder_.getMessageOrBuilder();
      } else {
        if (wKTCase_ == 11) {
          return (io.github.yu31.protoc.pb.pbjson.TypeEnum) wKT_;
        }
        return io.github.yu31.protoc.pb.pbjson.TypeEnum.getDefaultInstance();
      }
    }
    /**
     * <code>.json.TypeEnum enum = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.github.yu31.protoc.pb.pbjson.TypeEnum, io.github.yu31.protoc.pb.pbjson.TypeEnum.Builder, io.github.yu31.protoc.pb.pbjson.TypeEnumOrBuilder> 
        getEnumFieldBuilder() {
      if (enumBuilder_ == null) {
        if (!(wKTCase_ == 11)) {
          wKT_ = io.github.yu31.protoc.pb.pbjson.TypeEnum.getDefaultInstance();
        }
        enumBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.github.yu31.protoc.pb.pbjson.TypeEnum, io.github.yu31.protoc.pb.pbjson.TypeEnum.Builder, io.github.yu31.protoc.pb.pbjson.TypeEnumOrBuilder>(
                (io.github.yu31.protoc.pb.pbjson.TypeEnum) wKT_,
                getParentForChildren(),
                isClean());
        wKT_ = null;
      }
      wKTCase_ = 11;
      onChanged();;
      return enumBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.github.yu31.protoc.pb.pbjson.TypeAny, io.github.yu31.protoc.pb.pbjson.TypeAny.Builder, io.github.yu31.protoc.pb.pbjson.TypeAnyOrBuilder> anyBuilder_;
    /**
     * <code>.json.TypeAny any = 12;</code>
     * @return Whether the any field is set.
     */
    @java.lang.Override
    public boolean hasAny() {
      return wKTCase_ == 12;
    }
    /**
     * <code>.json.TypeAny any = 12;</code>
     * @return The any.
     */
    @java.lang.Override
    public io.github.yu31.protoc.pb.pbjson.TypeAny getAny() {
      if (anyBuilder_ == null) {
        if (wKTCase_ == 12) {
          return (io.github.yu31.protoc.pb.pbjson.TypeAny) wKT_;
        }
        return io.github.yu31.protoc.pb.pbjson.TypeAny.getDefaultInstance();
      } else {
        if (wKTCase_ == 12) {
          return anyBuilder_.getMessage();
        }
        return io.github.yu31.protoc.pb.pbjson.TypeAny.getDefaultInstance();
      }
    }
    /**
     * <code>.json.TypeAny any = 12;</code>
     */
    public Builder setAny(io.github.yu31.protoc.pb.pbjson.TypeAny value) {
      if (anyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        wKT_ = value;
        onChanged();
      } else {
        anyBuilder_.setMessage(value);
      }
      wKTCase_ = 12;
      return this;
    }
    /**
     * <code>.json.TypeAny any = 12;</code>
     */
    public Builder setAny(
        io.github.yu31.protoc.pb.pbjson.TypeAny.Builder builderForValue) {
      if (anyBuilder_ == null) {
        wKT_ = builderForValue.build();
        onChanged();
      } else {
        anyBuilder_.setMessage(builderForValue.build());
      }
      wKTCase_ = 12;
      return this;
    }
    /**
     * <code>.json.TypeAny any = 12;</code>
     */
    public Builder mergeAny(io.github.yu31.protoc.pb.pbjson.TypeAny value) {
      if (anyBuilder_ == null) {
        if (wKTCase_ == 12 &&
            wKT_ != io.github.yu31.protoc.pb.pbjson.TypeAny.getDefaultInstance()) {
          wKT_ = io.github.yu31.protoc.pb.pbjson.TypeAny.newBuilder((io.github.yu31.protoc.pb.pbjson.TypeAny) wKT_)
              .mergeFrom(value).buildPartial();
        } else {
          wKT_ = value;
        }
        onChanged();
      } else {
        if (wKTCase_ == 12) {
          anyBuilder_.mergeFrom(value);
        }
        anyBuilder_.setMessage(value);
      }
      wKTCase_ = 12;
      return this;
    }
    /**
     * <code>.json.TypeAny any = 12;</code>
     */
    public Builder clearAny() {
      if (anyBuilder_ == null) {
        if (wKTCase_ == 12) {
          wKTCase_ = 0;
          wKT_ = null;
          onChanged();
        }
      } else {
        if (wKTCase_ == 12) {
          wKTCase_ = 0;
          wKT_ = null;
        }
        anyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.json.TypeAny any = 12;</code>
     */
    public io.github.yu31.protoc.pb.pbjson.TypeAny.Builder getAnyBuilder() {
      return getAnyFieldBuilder().getBuilder();
    }
    /**
     * <code>.json.TypeAny any = 12;</code>
     */
    @java.lang.Override
    public io.github.yu31.protoc.pb.pbjson.TypeAnyOrBuilder getAnyOrBuilder() {
      if ((wKTCase_ == 12) && (anyBuilder_ != null)) {
        return anyBuilder_.getMessageOrBuilder();
      } else {
        if (wKTCase_ == 12) {
          return (io.github.yu31.protoc.pb.pbjson.TypeAny) wKT_;
        }
        return io.github.yu31.protoc.pb.pbjson.TypeAny.getDefaultInstance();
      }
    }
    /**
     * <code>.json.TypeAny any = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.github.yu31.protoc.pb.pbjson.TypeAny, io.github.yu31.protoc.pb.pbjson.TypeAny.Builder, io.github.yu31.protoc.pb.pbjson.TypeAnyOrBuilder> 
        getAnyFieldBuilder() {
      if (anyBuilder_ == null) {
        if (!(wKTCase_ == 12)) {
          wKT_ = io.github.yu31.protoc.pb.pbjson.TypeAny.getDefaultInstance();
        }
        anyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.github.yu31.protoc.pb.pbjson.TypeAny, io.github.yu31.protoc.pb.pbjson.TypeAny.Builder, io.github.yu31.protoc.pb.pbjson.TypeAnyOrBuilder>(
                (io.github.yu31.protoc.pb.pbjson.TypeAny) wKT_,
                getParentForChildren(),
                isClean());
        wKT_ = null;
      }
      wKTCase_ = 12;
      onChanged();;
      return anyBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.github.yu31.protoc.pb.pbjson.TypeDuration, io.github.yu31.protoc.pb.pbjson.TypeDuration.Builder, io.github.yu31.protoc.pb.pbjson.TypeDurationOrBuilder> durationBuilder_;
    /**
     * <code>.json.TypeDuration duration = 13;</code>
     * @return Whether the duration field is set.
     */
    @java.lang.Override
    public boolean hasDuration() {
      return wKTCase_ == 13;
    }
    /**
     * <code>.json.TypeDuration duration = 13;</code>
     * @return The duration.
     */
    @java.lang.Override
    public io.github.yu31.protoc.pb.pbjson.TypeDuration getDuration() {
      if (durationBuilder_ == null) {
        if (wKTCase_ == 13) {
          return (io.github.yu31.protoc.pb.pbjson.TypeDuration) wKT_;
        }
        return io.github.yu31.protoc.pb.pbjson.TypeDuration.getDefaultInstance();
      } else {
        if (wKTCase_ == 13) {
          return durationBuilder_.getMessage();
        }
        return io.github.yu31.protoc.pb.pbjson.TypeDuration.getDefaultInstance();
      }
    }
    /**
     * <code>.json.TypeDuration duration = 13;</code>
     */
    public Builder setDuration(io.github.yu31.protoc.pb.pbjson.TypeDuration value) {
      if (durationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        wKT_ = value;
        onChanged();
      } else {
        durationBuilder_.setMessage(value);
      }
      wKTCase_ = 13;
      return this;
    }
    /**
     * <code>.json.TypeDuration duration = 13;</code>
     */
    public Builder setDuration(
        io.github.yu31.protoc.pb.pbjson.TypeDuration.Builder builderForValue) {
      if (durationBuilder_ == null) {
        wKT_ = builderForValue.build();
        onChanged();
      } else {
        durationBuilder_.setMessage(builderForValue.build());
      }
      wKTCase_ = 13;
      return this;
    }
    /**
     * <code>.json.TypeDuration duration = 13;</code>
     */
    public Builder mergeDuration(io.github.yu31.protoc.pb.pbjson.TypeDuration value) {
      if (durationBuilder_ == null) {
        if (wKTCase_ == 13 &&
            wKT_ != io.github.yu31.protoc.pb.pbjson.TypeDuration.getDefaultInstance()) {
          wKT_ = io.github.yu31.protoc.pb.pbjson.TypeDuration.newBuilder((io.github.yu31.protoc.pb.pbjson.TypeDuration) wKT_)
              .mergeFrom(value).buildPartial();
        } else {
          wKT_ = value;
        }
        onChanged();
      } else {
        if (wKTCase_ == 13) {
          durationBuilder_.mergeFrom(value);
        }
        durationBuilder_.setMessage(value);
      }
      wKTCase_ = 13;
      return this;
    }
    /**
     * <code>.json.TypeDuration duration = 13;</code>
     */
    public Builder clearDuration() {
      if (durationBuilder_ == null) {
        if (wKTCase_ == 13) {
          wKTCase_ = 0;
          wKT_ = null;
          onChanged();
        }
      } else {
        if (wKTCase_ == 13) {
          wKTCase_ = 0;
          wKT_ = null;
        }
        durationBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.json.TypeDuration duration = 13;</code>
     */
    public io.github.yu31.protoc.pb.pbjson.TypeDuration.Builder getDurationBuilder() {
      return getDurationFieldBuilder().getBuilder();
    }
    /**
     * <code>.json.TypeDuration duration = 13;</code>
     */
    @java.lang.Override
    public io.github.yu31.protoc.pb.pbjson.TypeDurationOrBuilder getDurationOrBuilder() {
      if ((wKTCase_ == 13) && (durationBuilder_ != null)) {
        return durationBuilder_.getMessageOrBuilder();
      } else {
        if (wKTCase_ == 13) {
          return (io.github.yu31.protoc.pb.pbjson.TypeDuration) wKT_;
        }
        return io.github.yu31.protoc.pb.pbjson.TypeDuration.getDefaultInstance();
      }
    }
    /**
     * <code>.json.TypeDuration duration = 13;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.github.yu31.protoc.pb.pbjson.TypeDuration, io.github.yu31.protoc.pb.pbjson.TypeDuration.Builder, io.github.yu31.protoc.pb.pbjson.TypeDurationOrBuilder> 
        getDurationFieldBuilder() {
      if (durationBuilder_ == null) {
        if (!(wKTCase_ == 13)) {
          wKT_ = io.github.yu31.protoc.pb.pbjson.TypeDuration.getDefaultInstance();
        }
        durationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.github.yu31.protoc.pb.pbjson.TypeDuration, io.github.yu31.protoc.pb.pbjson.TypeDuration.Builder, io.github.yu31.protoc.pb.pbjson.TypeDurationOrBuilder>(
                (io.github.yu31.protoc.pb.pbjson.TypeDuration) wKT_,
                getParentForChildren(),
                isClean());
        wKT_ = null;
      }
      wKTCase_ = 13;
      onChanged();;
      return durationBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.github.yu31.protoc.pb.pbjson.TypeTimestamp, io.github.yu31.protoc.pb.pbjson.TypeTimestamp.Builder, io.github.yu31.protoc.pb.pbjson.TypeTimestampOrBuilder> timestampBuilder_;
    /**
     * <code>.json.TypeTimestamp timestamp = 14;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return wKTCase_ == 14;
    }
    /**
     * <code>.json.TypeTimestamp timestamp = 14;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public io.github.yu31.protoc.pb.pbjson.TypeTimestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        if (wKTCase_ == 14) {
          return (io.github.yu31.protoc.pb.pbjson.TypeTimestamp) wKT_;
        }
        return io.github.yu31.protoc.pb.pbjson.TypeTimestamp.getDefaultInstance();
      } else {
        if (wKTCase_ == 14) {
          return timestampBuilder_.getMessage();
        }
        return io.github.yu31.protoc.pb.pbjson.TypeTimestamp.getDefaultInstance();
      }
    }
    /**
     * <code>.json.TypeTimestamp timestamp = 14;</code>
     */
    public Builder setTimestamp(io.github.yu31.protoc.pb.pbjson.TypeTimestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        wKT_ = value;
        onChanged();
      } else {
        timestampBuilder_.setMessage(value);
      }
      wKTCase_ = 14;
      return this;
    }
    /**
     * <code>.json.TypeTimestamp timestamp = 14;</code>
     */
    public Builder setTimestamp(
        io.github.yu31.protoc.pb.pbjson.TypeTimestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        wKT_ = builderForValue.build();
        onChanged();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }
      wKTCase_ = 14;
      return this;
    }
    /**
     * <code>.json.TypeTimestamp timestamp = 14;</code>
     */
    public Builder mergeTimestamp(io.github.yu31.protoc.pb.pbjson.TypeTimestamp value) {
      if (timestampBuilder_ == null) {
        if (wKTCase_ == 14 &&
            wKT_ != io.github.yu31.protoc.pb.pbjson.TypeTimestamp.getDefaultInstance()) {
          wKT_ = io.github.yu31.protoc.pb.pbjson.TypeTimestamp.newBuilder((io.github.yu31.protoc.pb.pbjson.TypeTimestamp) wKT_)
              .mergeFrom(value).buildPartial();
        } else {
          wKT_ = value;
        }
        onChanged();
      } else {
        if (wKTCase_ == 14) {
          timestampBuilder_.mergeFrom(value);
        }
        timestampBuilder_.setMessage(value);
      }
      wKTCase_ = 14;
      return this;
    }
    /**
     * <code>.json.TypeTimestamp timestamp = 14;</code>
     */
    public Builder clearTimestamp() {
      if (timestampBuilder_ == null) {
        if (wKTCase_ == 14) {
          wKTCase_ = 0;
          wKT_ = null;
          onChanged();
        }
      } else {
        if (wKTCase_ == 14) {
          wKTCase_ = 0;
          wKT_ = null;
        }
        timestampBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.json.TypeTimestamp timestamp = 14;</code>
     */
    public io.github.yu31.protoc.pb.pbjson.TypeTimestamp.Builder getTimestampBuilder() {
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.json.TypeTimestamp timestamp = 14;</code>
     */
    @java.lang.Override
    public io.github.yu31.protoc.pb.pbjson.TypeTimestampOrBuilder getTimestampOrBuilder() {
      if ((wKTCase_ == 14) && (timestampBuilder_ != null)) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        if (wKTCase_ == 14) {
          return (io.github.yu31.protoc.pb.pbjson.TypeTimestamp) wKT_;
        }
        return io.github.yu31.protoc.pb.pbjson.TypeTimestamp.getDefaultInstance();
      }
    }
    /**
     * <code>.json.TypeTimestamp timestamp = 14;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.github.yu31.protoc.pb.pbjson.TypeTimestamp, io.github.yu31.protoc.pb.pbjson.TypeTimestamp.Builder, io.github.yu31.protoc.pb.pbjson.TypeTimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        if (!(wKTCase_ == 14)) {
          wKT_ = io.github.yu31.protoc.pb.pbjson.TypeTimestamp.getDefaultInstance();
        }
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.github.yu31.protoc.pb.pbjson.TypeTimestamp, io.github.yu31.protoc.pb.pbjson.TypeTimestamp.Builder, io.github.yu31.protoc.pb.pbjson.TypeTimestampOrBuilder>(
                (io.github.yu31.protoc.pb.pbjson.TypeTimestamp) wKT_,
                getParentForChildren(),
                isClean());
        wKT_ = null;
      }
      wKTCase_ = 14;
      onChanged();;
      return timestampBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:json.FieldOptions)
  }

  // @@protoc_insertion_point(class_scope:json.FieldOptions)
  private static final io.github.yu31.protoc.pb.pbjson.FieldOptions DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.yu31.protoc.pb.pbjson.FieldOptions();
  }

  public static io.github.yu31.protoc.pb.pbjson.FieldOptions getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FieldOptions>
      PARSER = new com.google.protobuf.AbstractParser<FieldOptions>() {
    @java.lang.Override
    public FieldOptions parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FieldOptions(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FieldOptions> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FieldOptions> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.yu31.protoc.pb.pbjson.FieldOptions getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

