// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: json.proto

package io.github.yu31.protoc.pb.pbjson;

public interface TypeStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:json.TypeString)
    com.google.protobuf.MessageOrBuilder {
}
