// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: json.proto

package io.github.yu31.protoc.pb.pbjson;

/**
 * Protobuf type {@code json.TypeDuration}
 */
public final class TypeDuration extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:json.TypeDuration)
    TypeDurationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TypeDuration.newBuilder() to construct.
  private TypeDuration(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TypeDuration() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TypeDuration();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TypeDuration(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            format_ = input.readBool();
            formatCase_ = 1;
            break;
          }
          case 16: {
            format_ = input.readBool();
            formatCase_ = 2;
            break;
          }
          case 24: {
            format_ = input.readBool();
            formatCase_ = 3;
            break;
          }
          case 32: {
            format_ = input.readBool();
            formatCase_ = 4;
            break;
          }
          case 40: {
            format_ = input.readBool();
            formatCase_ = 5;
            break;
          }
          case 48: {
            format_ = input.readBool();
            formatCase_ = 6;
            break;
          }
          case 56: {
            format_ = input.readBool();
            formatCase_ = 7;
            break;
          }
          case 64: {
            format_ = input.readBool();
            formatCase_ = 8;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.yu31.protoc.pb.pbjson.PBJSON.internal_static_json_TypeDuration_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.yu31.protoc.pb.pbjson.PBJSON.internal_static_json_TypeDuration_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.yu31.protoc.pb.pbjson.TypeDuration.class, io.github.yu31.protoc.pb.pbjson.TypeDuration.Builder.class);
  }

  private int formatCase_ = 0;
  private java.lang.Object format_;
  public enum FormatCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    NATIVE(1),
    STRING(2),
    NANOSECONDS(3),
    MICROSECONDS(4),
    MILLISECONDS(5),
    SECONDS(6),
    MINUTES(7),
    HOURS(8),
    FORMAT_NOT_SET(0);
    private final int value;
    private FormatCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FormatCase valueOf(int value) {
      return forNumber(value);
    }

    public static FormatCase forNumber(int value) {
      switch (value) {
        case 1: return NATIVE;
        case 2: return STRING;
        case 3: return NANOSECONDS;
        case 4: return MICROSECONDS;
        case 5: return MILLISECONDS;
        case 6: return SECONDS;
        case 7: return MINUTES;
        case 8: return HOURS;
        case 0: return FORMAT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public FormatCase
  getFormatCase() {
    return FormatCase.forNumber(
        formatCase_);
  }

  public static final int NATIVE_FIELD_NUMBER = 1;
  /**
   * <code>bool native = 1;</code>
   * @return Whether the native field is set.
   */
  @java.lang.Override
  public boolean hasNative() {
    return formatCase_ == 1;
  }
  /**
   * <code>bool native = 1;</code>
   * @return The native.
   */
  @java.lang.Override
  public boolean getNative() {
    if (formatCase_ == 1) {
      return (java.lang.Boolean) format_;
    }
    return false;
  }

  public static final int STRING_FIELD_NUMBER = 2;
  /**
   * <code>bool string = 2;</code>
   * @return Whether the string field is set.
   */
  @java.lang.Override
  public boolean hasString() {
    return formatCase_ == 2;
  }
  /**
   * <code>bool string = 2;</code>
   * @return The string.
   */
  @java.lang.Override
  public boolean getString() {
    if (formatCase_ == 2) {
      return (java.lang.Boolean) format_;
    }
    return false;
  }

  public static final int NANOSECONDS_FIELD_NUMBER = 3;
  /**
   * <code>bool nanoseconds = 3;</code>
   * @return Whether the nanoseconds field is set.
   */
  @java.lang.Override
  public boolean hasNanoseconds() {
    return formatCase_ == 3;
  }
  /**
   * <code>bool nanoseconds = 3;</code>
   * @return The nanoseconds.
   */
  @java.lang.Override
  public boolean getNanoseconds() {
    if (formatCase_ == 3) {
      return (java.lang.Boolean) format_;
    }
    return false;
  }

  public static final int MICROSECONDS_FIELD_NUMBER = 4;
  /**
   * <code>bool microseconds = 4;</code>
   * @return Whether the microseconds field is set.
   */
  @java.lang.Override
  public boolean hasMicroseconds() {
    return formatCase_ == 4;
  }
  /**
   * <code>bool microseconds = 4;</code>
   * @return The microseconds.
   */
  @java.lang.Override
  public boolean getMicroseconds() {
    if (formatCase_ == 4) {
      return (java.lang.Boolean) format_;
    }
    return false;
  }

  public static final int MILLISECONDS_FIELD_NUMBER = 5;
  /**
   * <code>bool milliseconds = 5;</code>
   * @return Whether the milliseconds field is set.
   */
  @java.lang.Override
  public boolean hasMilliseconds() {
    return formatCase_ == 5;
  }
  /**
   * <code>bool milliseconds = 5;</code>
   * @return The milliseconds.
   */
  @java.lang.Override
  public boolean getMilliseconds() {
    if (formatCase_ == 5) {
      return (java.lang.Boolean) format_;
    }
    return false;
  }

  public static final int SECONDS_FIELD_NUMBER = 6;
  /**
   * <code>bool seconds = 6;</code>
   * @return Whether the seconds field is set.
   */
  @java.lang.Override
  public boolean hasSeconds() {
    return formatCase_ == 6;
  }
  /**
   * <code>bool seconds = 6;</code>
   * @return The seconds.
   */
  @java.lang.Override
  public boolean getSeconds() {
    if (formatCase_ == 6) {
      return (java.lang.Boolean) format_;
    }
    return false;
  }

  public static final int MINUTES_FIELD_NUMBER = 7;
  /**
   * <code>bool minutes = 7;</code>
   * @return Whether the minutes field is set.
   */
  @java.lang.Override
  public boolean hasMinutes() {
    return formatCase_ == 7;
  }
  /**
   * <code>bool minutes = 7;</code>
   * @return The minutes.
   */
  @java.lang.Override
  public boolean getMinutes() {
    if (formatCase_ == 7) {
      return (java.lang.Boolean) format_;
    }
    return false;
  }

  public static final int HOURS_FIELD_NUMBER = 8;
  /**
   * <code>bool hours = 8;</code>
   * @return Whether the hours field is set.
   */
  @java.lang.Override
  public boolean hasHours() {
    return formatCase_ == 8;
  }
  /**
   * <code>bool hours = 8;</code>
   * @return The hours.
   */
  @java.lang.Override
  public boolean getHours() {
    if (formatCase_ == 8) {
      return (java.lang.Boolean) format_;
    }
    return false;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (formatCase_ == 1) {
      output.writeBool(
          1, (boolean)((java.lang.Boolean) format_));
    }
    if (formatCase_ == 2) {
      output.writeBool(
          2, (boolean)((java.lang.Boolean) format_));
    }
    if (formatCase_ == 3) {
      output.writeBool(
          3, (boolean)((java.lang.Boolean) format_));
    }
    if (formatCase_ == 4) {
      output.writeBool(
          4, (boolean)((java.lang.Boolean) format_));
    }
    if (formatCase_ == 5) {
      output.writeBool(
          5, (boolean)((java.lang.Boolean) format_));
    }
    if (formatCase_ == 6) {
      output.writeBool(
          6, (boolean)((java.lang.Boolean) format_));
    }
    if (formatCase_ == 7) {
      output.writeBool(
          7, (boolean)((java.lang.Boolean) format_));
    }
    if (formatCase_ == 8) {
      output.writeBool(
          8, (boolean)((java.lang.Boolean) format_));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (formatCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            1, (boolean)((java.lang.Boolean) format_));
    }
    if (formatCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            2, (boolean)((java.lang.Boolean) format_));
    }
    if (formatCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            3, (boolean)((java.lang.Boolean) format_));
    }
    if (formatCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            4, (boolean)((java.lang.Boolean) format_));
    }
    if (formatCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            5, (boolean)((java.lang.Boolean) format_));
    }
    if (formatCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            6, (boolean)((java.lang.Boolean) format_));
    }
    if (formatCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            7, (boolean)((java.lang.Boolean) format_));
    }
    if (formatCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            8, (boolean)((java.lang.Boolean) format_));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.yu31.protoc.pb.pbjson.TypeDuration)) {
      return super.equals(obj);
    }
    io.github.yu31.protoc.pb.pbjson.TypeDuration other = (io.github.yu31.protoc.pb.pbjson.TypeDuration) obj;

    if (!getFormatCase().equals(other.getFormatCase())) return false;
    switch (formatCase_) {
      case 1:
        if (getNative()
            != other.getNative()) return false;
        break;
      case 2:
        if (getString()
            != other.getString()) return false;
        break;
      case 3:
        if (getNanoseconds()
            != other.getNanoseconds()) return false;
        break;
      case 4:
        if (getMicroseconds()
            != other.getMicroseconds()) return false;
        break;
      case 5:
        if (getMilliseconds()
            != other.getMilliseconds()) return false;
        break;
      case 6:
        if (getSeconds()
            != other.getSeconds()) return false;
        break;
      case 7:
        if (getMinutes()
            != other.getMinutes()) return false;
        break;
      case 8:
        if (getHours()
            != other.getHours()) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (formatCase_) {
      case 1:
        hash = (37 * hash) + NATIVE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getNative());
        break;
      case 2:
        hash = (37 * hash) + STRING_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getString());
        break;
      case 3:
        hash = (37 * hash) + NANOSECONDS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getNanoseconds());
        break;
      case 4:
        hash = (37 * hash) + MICROSECONDS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getMicroseconds());
        break;
      case 5:
        hash = (37 * hash) + MILLISECONDS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getMilliseconds());
        break;
      case 6:
        hash = (37 * hash) + SECONDS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getSeconds());
        break;
      case 7:
        hash = (37 * hash) + MINUTES_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getMinutes());
        break;
      case 8:
        hash = (37 * hash) + HOURS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getHours());
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.yu31.protoc.pb.pbjson.TypeDuration parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.yu31.protoc.pb.pbjson.TypeDuration parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbjson.TypeDuration parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.yu31.protoc.pb.pbjson.TypeDuration parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbjson.TypeDuration parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.yu31.protoc.pb.pbjson.TypeDuration parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbjson.TypeDuration parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.yu31.protoc.pb.pbjson.TypeDuration parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbjson.TypeDuration parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.github.yu31.protoc.pb.pbjson.TypeDuration parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.yu31.protoc.pb.pbjson.TypeDuration parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.yu31.protoc.pb.pbjson.TypeDuration parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.yu31.protoc.pb.pbjson.TypeDuration prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code json.TypeDuration}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:json.TypeDuration)
      io.github.yu31.protoc.pb.pbjson.TypeDurationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.yu31.protoc.pb.pbjson.PBJSON.internal_static_json_TypeDuration_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.yu31.protoc.pb.pbjson.PBJSON.internal_static_json_TypeDuration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.yu31.protoc.pb.pbjson.TypeDuration.class, io.github.yu31.protoc.pb.pbjson.TypeDuration.Builder.class);
    }

    // Construct using io.github.yu31.protoc.pb.pbjson.TypeDuration.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      formatCase_ = 0;
      format_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.yu31.protoc.pb.pbjson.PBJSON.internal_static_json_TypeDuration_descriptor;
    }

    @java.lang.Override
    public io.github.yu31.protoc.pb.pbjson.TypeDuration getDefaultInstanceForType() {
      return io.github.yu31.protoc.pb.pbjson.TypeDuration.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.yu31.protoc.pb.pbjson.TypeDuration build() {
      io.github.yu31.protoc.pb.pbjson.TypeDuration result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.yu31.protoc.pb.pbjson.TypeDuration buildPartial() {
      io.github.yu31.protoc.pb.pbjson.TypeDuration result = new io.github.yu31.protoc.pb.pbjson.TypeDuration(this);
      if (formatCase_ == 1) {
        result.format_ = format_;
      }
      if (formatCase_ == 2) {
        result.format_ = format_;
      }
      if (formatCase_ == 3) {
        result.format_ = format_;
      }
      if (formatCase_ == 4) {
        result.format_ = format_;
      }
      if (formatCase_ == 5) {
        result.format_ = format_;
      }
      if (formatCase_ == 6) {
        result.format_ = format_;
      }
      if (formatCase_ == 7) {
        result.format_ = format_;
      }
      if (formatCase_ == 8) {
        result.format_ = format_;
      }
      result.formatCase_ = formatCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.yu31.protoc.pb.pbjson.TypeDuration) {
        return mergeFrom((io.github.yu31.protoc.pb.pbjson.TypeDuration)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.yu31.protoc.pb.pbjson.TypeDuration other) {
      if (other == io.github.yu31.protoc.pb.pbjson.TypeDuration.getDefaultInstance()) return this;
      switch (other.getFormatCase()) {
        case NATIVE: {
          setNative(other.getNative());
          break;
        }
        case STRING: {
          setString(other.getString());
          break;
        }
        case NANOSECONDS: {
          setNanoseconds(other.getNanoseconds());
          break;
        }
        case MICROSECONDS: {
          setMicroseconds(other.getMicroseconds());
          break;
        }
        case MILLISECONDS: {
          setMilliseconds(other.getMilliseconds());
          break;
        }
        case SECONDS: {
          setSeconds(other.getSeconds());
          break;
        }
        case MINUTES: {
          setMinutes(other.getMinutes());
          break;
        }
        case HOURS: {
          setHours(other.getHours());
          break;
        }
        case FORMAT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.github.yu31.protoc.pb.pbjson.TypeDuration parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.github.yu31.protoc.pb.pbjson.TypeDuration) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int formatCase_ = 0;
    private java.lang.Object format_;
    public FormatCase
        getFormatCase() {
      return FormatCase.forNumber(
          formatCase_);
    }

    public Builder clearFormat() {
      formatCase_ = 0;
      format_ = null;
      onChanged();
      return this;
    }


    /**
     * <code>bool native = 1;</code>
     * @return Whether the native field is set.
     */
    public boolean hasNative() {
      return formatCase_ == 1;
    }
    /**
     * <code>bool native = 1;</code>
     * @return The native.
     */
    public boolean getNative() {
      if (formatCase_ == 1) {
        return (java.lang.Boolean) format_;
      }
      return false;
    }
    /**
     * <code>bool native = 1;</code>
     * @param value The native to set.
     * @return This builder for chaining.
     */
    public Builder setNative(boolean value) {
      formatCase_ = 1;
      format_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool native = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNative() {
      if (formatCase_ == 1) {
        formatCase_ = 0;
        format_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>bool string = 2;</code>
     * @return Whether the string field is set.
     */
    public boolean hasString() {
      return formatCase_ == 2;
    }
    /**
     * <code>bool string = 2;</code>
     * @return The string.
     */
    public boolean getString() {
      if (formatCase_ == 2) {
        return (java.lang.Boolean) format_;
      }
      return false;
    }
    /**
     * <code>bool string = 2;</code>
     * @param value The string to set.
     * @return This builder for chaining.
     */
    public Builder setString(boolean value) {
      formatCase_ = 2;
      format_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool string = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearString() {
      if (formatCase_ == 2) {
        formatCase_ = 0;
        format_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>bool nanoseconds = 3;</code>
     * @return Whether the nanoseconds field is set.
     */
    public boolean hasNanoseconds() {
      return formatCase_ == 3;
    }
    /**
     * <code>bool nanoseconds = 3;</code>
     * @return The nanoseconds.
     */
    public boolean getNanoseconds() {
      if (formatCase_ == 3) {
        return (java.lang.Boolean) format_;
      }
      return false;
    }
    /**
     * <code>bool nanoseconds = 3;</code>
     * @param value The nanoseconds to set.
     * @return This builder for chaining.
     */
    public Builder setNanoseconds(boolean value) {
      formatCase_ = 3;
      format_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool nanoseconds = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNanoseconds() {
      if (formatCase_ == 3) {
        formatCase_ = 0;
        format_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>bool microseconds = 4;</code>
     * @return Whether the microseconds field is set.
     */
    public boolean hasMicroseconds() {
      return formatCase_ == 4;
    }
    /**
     * <code>bool microseconds = 4;</code>
     * @return The microseconds.
     */
    public boolean getMicroseconds() {
      if (formatCase_ == 4) {
        return (java.lang.Boolean) format_;
      }
      return false;
    }
    /**
     * <code>bool microseconds = 4;</code>
     * @param value The microseconds to set.
     * @return This builder for chaining.
     */
    public Builder setMicroseconds(boolean value) {
      formatCase_ = 4;
      format_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool microseconds = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMicroseconds() {
      if (formatCase_ == 4) {
        formatCase_ = 0;
        format_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>bool milliseconds = 5;</code>
     * @return Whether the milliseconds field is set.
     */
    public boolean hasMilliseconds() {
      return formatCase_ == 5;
    }
    /**
     * <code>bool milliseconds = 5;</code>
     * @return The milliseconds.
     */
    public boolean getMilliseconds() {
      if (formatCase_ == 5) {
        return (java.lang.Boolean) format_;
      }
      return false;
    }
    /**
     * <code>bool milliseconds = 5;</code>
     * @param value The milliseconds to set.
     * @return This builder for chaining.
     */
    public Builder setMilliseconds(boolean value) {
      formatCase_ = 5;
      format_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool milliseconds = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMilliseconds() {
      if (formatCase_ == 5) {
        formatCase_ = 0;
        format_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>bool seconds = 6;</code>
     * @return Whether the seconds field is set.
     */
    public boolean hasSeconds() {
      return formatCase_ == 6;
    }
    /**
     * <code>bool seconds = 6;</code>
     * @return The seconds.
     */
    public boolean getSeconds() {
      if (formatCase_ == 6) {
        return (java.lang.Boolean) format_;
      }
      return false;
    }
    /**
     * <code>bool seconds = 6;</code>
     * @param value The seconds to set.
     * @return This builder for chaining.
     */
    public Builder setSeconds(boolean value) {
      formatCase_ = 6;
      format_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool seconds = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeconds() {
      if (formatCase_ == 6) {
        formatCase_ = 0;
        format_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>bool minutes = 7;</code>
     * @return Whether the minutes field is set.
     */
    public boolean hasMinutes() {
      return formatCase_ == 7;
    }
    /**
     * <code>bool minutes = 7;</code>
     * @return The minutes.
     */
    public boolean getMinutes() {
      if (formatCase_ == 7) {
        return (java.lang.Boolean) format_;
      }
      return false;
    }
    /**
     * <code>bool minutes = 7;</code>
     * @param value The minutes to set.
     * @return This builder for chaining.
     */
    public Builder setMinutes(boolean value) {
      formatCase_ = 7;
      format_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool minutes = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinutes() {
      if (formatCase_ == 7) {
        formatCase_ = 0;
        format_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>bool hours = 8;</code>
     * @return Whether the hours field is set.
     */
    public boolean hasHours() {
      return formatCase_ == 8;
    }
    /**
     * <code>bool hours = 8;</code>
     * @return The hours.
     */
    public boolean getHours() {
      if (formatCase_ == 8) {
        return (java.lang.Boolean) format_;
      }
      return false;
    }
    /**
     * <code>bool hours = 8;</code>
     * @param value The hours to set.
     * @return This builder for chaining.
     */
    public Builder setHours(boolean value) {
      formatCase_ = 8;
      format_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool hours = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearHours() {
      if (formatCase_ == 8) {
        formatCase_ = 0;
        format_ = null;
        onChanged();
      }
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:json.TypeDuration)
  }

  // @@protoc_insertion_point(class_scope:json.TypeDuration)
  private static final io.github.yu31.protoc.pb.pbjson.TypeDuration DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.yu31.protoc.pb.pbjson.TypeDuration();
  }

  public static io.github.yu31.protoc.pb.pbjson.TypeDuration getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TypeDuration>
      PARSER = new com.google.protobuf.AbstractParser<TypeDuration>() {
    @java.lang.Override
    public TypeDuration parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TypeDuration(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TypeDuration> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TypeDuration> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.yu31.protoc.pb.pbjson.TypeDuration getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

