// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: json.proto

package io.github.yu31.protoc.pb.pbjson;

public interface TypeTimestampOrBuilder extends
    // @@protoc_insertion_point(interface_extends:json.TypeTimestamp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool native = 1;</code>
   * @return Whether the native field is set.
   */
  boolean hasNative();
  /**
   * <code>bool native = 1;</code>
   * @return The native.
   */
  boolean getNative();

  /**
   * <code>.json.TypeTimestamp.TimeLayout time_layout = 2;</code>
   * @return Whether the timeLayout field is set.
   */
  boolean hasTimeLayout();
  /**
   * <code>.json.TypeTimestamp.TimeLayout time_layout = 2;</code>
   * @return The timeLayout.
   */
  io.github.yu31.protoc.pb.pbjson.TypeTimestamp.TimeLayout getTimeLayout();
  /**
   * <code>.json.TypeTimestamp.TimeLayout time_layout = 2;</code>
   */
  io.github.yu31.protoc.pb.pbjson.TypeTimestamp.TimeLayoutOrBuilder getTimeLayoutOrBuilder();

  /**
   * <code>bool unix_nano = 3;</code>
   * @return Whether the unixNano field is set.
   */
  boolean hasUnixNano();
  /**
   * <code>bool unix_nano = 3;</code>
   * @return The unixNano.
   */
  boolean getUnixNano();

  /**
   * <code>bool unix_micro = 4;</code>
   * @return Whether the unixMicro field is set.
   */
  boolean hasUnixMicro();
  /**
   * <code>bool unix_micro = 4;</code>
   * @return The unixMicro.
   */
  boolean getUnixMicro();

  /**
   * <code>bool unix_milli = 5;</code>
   * @return Whether the unixMilli field is set.
   */
  boolean hasUnixMilli();
  /**
   * <code>bool unix_milli = 5;</code>
   * @return The unixMilli.
   */
  boolean getUnixMilli();

  /**
   * <code>bool unix_sec = 6;</code>
   * @return Whether the unixSec field is set.
   */
  boolean hasUnixSec();
  /**
   * <code>bool unix_sec = 6;</code>
   * @return The unixSec.
   */
  boolean getUnixSec();

  public io.github.yu31.protoc.pb.pbjson.TypeTimestamp.FormatCase getFormatCase();
}
